SELECT 
	"CL"."NAME" AS "CL_NAME",
	"MJ"."name" AS "J_NAME",
	"MJ"."code" AS "J_CODE"
FROM "CLIENT_LEGALENTITY" AS "CL" JOIN "MASTER.JURISDICTION" AS "MJ" ON "CL"."JURISDICTION_ID" = "MJ"."ID";

CREATE COLUMN TABLE "CLIENT_LEGALENTITY" ("ID" INTEGER CS_INT NOT NULL , "NAME" NVARCHAR(248), "JURISDICTION_JURISDICTIONID" INTEGER CS_INT, PRIMARY KEY ("ID")) WITH ASSOCIATIONS( JOIN "MTA_DT_POC_DT_POC_HDI_CLIENT_1"."MASTER_JURISDICTION" AS "JURISDICTION" ON "JURISDICTION"."JURISDICTIONID" = "JURISDICTION_JURISDICTIONID")  UNLOAD PRIORITY 5  AUTO MERGE 

CREATE COLUMN TABLE "MTA_DT_POC_DT_POC_HDI_CLIENT_1"."CLIENT_LEGALENTITY" ("ID" INTEGER CS_INT NOT NULL , "NAME" NVARCHAR(248), "JURISDICTION_JURISDICTIONID" INTEGER CS_INT, PRIMARY KEY ("ID")) WITH ASSOCIATIONS( JOIN "MTA_DT_POC_DT_POC_HDI_CLIENT_1"."MASTER_JURISDICTION" AS "JURISDICTION" ON "JURISDICTION"."JURISDICTIONID" = "JURISDICTION_JURISDICTIONID")  UNLOAD PRIORITY 5  AUTO MERGE 
